spring:
  application:
    name: zuul
  profiles:
    active: DEV


eureka:
  client:
    service-url:
     defaultZone: http://${eureka.user}:${eureka.password}@${eureka.url}:${eureka.port}/eureka

server:
  port: 9095
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 200
  routes:
    offerService:
      path: /offerService/**
      serviceId: offer